name: iuse-bluebuild-btw
description: just one geek's experiment with blue-build
base-image: ghcr.io/ublue-os/aurora-dx
image-version: 41
modules:
  - type: files
    files:
      - source: system
        destination: /
  - type: rpm-ostree
    repos: []
    install:
      - bat
      - borgbackup
      - cowsay
      - cronie
      - duf
      - eza
      - fd-find
      - fuzzel
      - git-delta
      - golang
      - httpie
      - iftop
      - konsole
      - neovim
      - pwgen
      - python3-neovim
      - ripgrep
      - syncthing
      - thefuck
      - tldr
      - yarnpkg
      - zsh-autosuggestions
      - zsh-syntax-highlighting
    remove: []
  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub"
      install:
        - com.brave.Browser
        - com.google.Chrome
        - com.microsoft.Edge
        - com.obsproject.Studio
        - io.github.ungoogled_software.ungoogled_chromium
        - org.chromium.Chromium
        - org.libreoffice.LibreOffice
        - org.mozilla.firefox
        - org.sqlitebrowser.sqlitebrowser
      remove: []
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
