name: iuse-bluebuild-btw
description: just one geek's experiment with blue-build
base-image: ghcr.io/ublue-os/aurora-dx
image-version: 40
modules:
  - type: files
    files:
      - usr: /usr # copies config/files/usr into your image's /usr.
                  # put configuration files you want in /etc/ on a booted system
                  # in /usr/etc/ in the image. read more in files module reference.
  - type: rpm-ostree
    repos:
    install:
      - bat
      - borgbackup
      - cowsay
      - duf
      - fd-find
      - fuzzel
      - git-delta
      - konsole
      - neovim
      - python3-neovim
      - ripgrep
      - syncthing
      - thefuck
      - yarnpkg
      - zsh-autosuggestions
      - zsh-syntax-highlighting
    remove:
  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub"
      install:
        - com.brave.Browser
        - com.google.Chrome
        - com.microsoft.Edge
        - com.obsproject.Studio
        - io.github.ungoogled_software.ungoogled_chromium
        - org.chromium.Chromium
        - org.mozilla.firefox
      remove:
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
